### ISSUE TITLE
破解版有啥不一样的吗？啥时候上传呀

### ISSUE THREAD

**Issue by gengxiz** [NiceDayk/Eudic-Macos-Crack#1]

**Comment by NiceDayk** [comment]
@gengxiz 

Mac版欧路词典激活与不激活，有什么区别，软件注册的地方写的很清楚，我就不再重复了。

破解版有什么不一样？破解版是可以免费激活软件的，使用破解版欧路词典，在输入注册码的地方输入任意内容（包括空内容，即什么都不输入），点击激活，均可激活软件。

破解版刚刚已经上传。

祝各位使用破解版欧路词典用的开心。         --------  来自雷锋的祝福
