### ISSUE TITLE
简化破解步骤的说明

### ISSUE THREAD

**Issue by githubcatheaven** [NiceDayk/Eudic-Macos-Crack#2]
1. 下载附件中原版dmg和破解文件
2. 安装欧路词典dmg
3. 进入 设置 - 在线功能 - 关闭所有检查和下载更新选项
4. 运行一次并关闭（不知是否必须，与视频保持一致）
5. 右键欧路词典app，选择【查看包内容】，进入 MacOS 目录（参考路径：/Applications/Eudic.app/Contents/MacOS）
6. 将目录内的 Eudic 文件删除
7. 用破解文件移入该目录内，改名为上面被删除的 Eudic。
8. 运行欧路词典app
9. 查看【注册信息】显示已注册

**Comment by NiceDayk** [comment]
@githubcatheaven 

 请问你这是在故意误导大家吗？ 我这是破解软件，具体怎么破解，我发的视频真是你这样描述的吗？

我按你的描述操作下来，并没有看到已注册。

大家要是都按你的步骤操作，结果没有看到已注册，是我在欺骗大家吗？
